### PR TITLE
Fixed issue #21 (undefined fills)

### PR DESCRIPTION
**Pull request by Happy-Ferret**
As requested, this should fix issue #21  by applying the correct fills of `#3e4347` to the three paths within `1f43f.svg` that were previously missing them.

See also Ranks/emojione#215

### CODE REVIEW

**Comment by 13rac1** [comment]
Awesome thank you!

Can you please amend the commit message to keep it consistent with the rest of the git history commit message style? Something like this:

```
svg: Fix missing eye color on squirrel

Fixes #21
Related https://github.com/Ranks/emojione/issues/215
```

**Comment by 13rac1** [comment]
I can rewrite before merge, let me know what works for you. Thanks!

**Comment by Happy-Ferret** [comment]
Whoops! Sorry for that.
Just changed it. Hope it's fine now.

**Comment by 13rac1** [comment]
Thank you! This will be in the next update. I'm waiting a bit longer to see if there are any other breaking bugs/issues before I make the v1.0.

**Pull request merged**
